[package]
name = "graphqlgen_apollo"
version = "0.1.0"
edition = "2021"

[dependencies]
graphqlgen_schema = { path = "../graphqlgen_schema" }

serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
tempfile = "3.19.1"
